apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: weu38af02-nodejs
  janus-idp.io/tekton: weu38af02-nodejs
  backstage.io/kubernetes-id: weu38af02-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: weu38af02-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
